// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfongkhekhdfkfhgsqke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmb25na2hla2hkZmtmaGdzcWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTM5NjQsImV4cCI6MjA2NDEyOTk2NH0.ravHgv4Gnuk8xudAs8urXmCbt61IXJZo1_3Uh9biGgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);